# -*- coding: utf-8 -*-
import getpass

# Form implementation generated from reading ui file 'ParentControl.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiMainWindow:
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.username = getpass.getuser()
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(210, 100, 321, 16))
        self.label_4.setObjectName("label_4")
        self.turn_parental_control = QtWidgets.QCheckBox(self.centralwidget)
        self.turn_parental_control.setGeometry(QtCore.QRect(600, 20, 191, 20))
        self.turn_parental_control.setStyleSheet("border: 1px solid #adb5bd;\n"
                                                 "  border-radius: 0.25em;\n"
                                                 "  margin-right: 0.5em;\n"
                                                 "  background-repeat: no-repeat;\n"
                                                 "  background-position: center center;\n"
                                                 "  background-size: 50% 50%;")
        self.turn_parental_control.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 50, 171, 51))
        self.pushButton.setStyleSheet("background-color: rgb(59, 130, 117);\n"
                                      "color: white;\n"
                                      "font-size: 16px;\n"
                                      "border-radius: 5px;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 140, 171, 51))
        self.pushButton_2.setStyleSheet("background-color: rgb(75, 165, 148);\n"
                                        "color: white;\n"
                                        "font-size: 16px;\n"
                                        "border-radius: 5px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 230, 171, 51))
        self.pushButton_3.setStyleSheet("background-color: rgb(75, 165, 148);\n"
                                        "color: white;\n"
                                        "font-size: 16px;\n"
                                        "border-radius: 5px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 320, 171, 51))
        self.pushButton_4.setStyleSheet("background-color: rgb(75, 165, 148);\n"
                                        "color: white;\n"
                                        "font-size: 16px;\n"
                                        "border-radius: 5px;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 400, 171, 51))
        self.pushButton_5.setStyleSheet("background-color: rgb(75, 165, 148);\n"
                                        "color: white;\n"
                                        "font-size: 15px;\n"
                                        "border-radius: 5px;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.button_details = QtWidgets.QPushButton(self.centralwidget)
        self.button_details.setGeometry(QtCore.QRect(20, 510, 111, 31))
        self.button_details.setObjectName("pushButton_6")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 480, 171, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(180, 50, 20, 511))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 271, 16))
        self.label.setObjectName("label")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 40, 781, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 70, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 400, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(210, 430, 321, 16))
        self.label_5.setObjectName("label_5")
        self.limit_time_monday = QtWidgets.QCheckBox(self.centralwidget)
        self.limit_time_monday.setGeometry(QtCore.QRect(220, 140, 241, 20))
        self.limit_time_monday.setStyleSheet("border: 1px solid #adb5bd;\n"
                                             "  border-radius: 0.25em;\n"
                                             "  margin-right: 0.5em;\n"
                                             "  background-repeat: no-repeat;\n"
                                             "  background-position: center center;\n"
                                             "  background-size: 50% 50%;")
        self.limit_time_monday.setObjectName("checkBox_2")
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(470, 140, 118, 24))
        self.timeEdit.setObjectName("timeEdit")
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit_2.setGeometry(QtCore.QRect(470, 180, 118, 24))
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.limit_time_tuesday = QtWidgets.QCheckBox(self.centralwidget)
        self.limit_time_tuesday.setGeometry(QtCore.QRect(220, 180, 241, 20))
        self.limit_time_tuesday.setStyleSheet("border: 1px solid #adb5bd;\n"
                                              "  border-radius: 0.25em;\n"
                                              "  margin-right: 0.5em;\n"
                                              "  background-repeat: no-repeat;\n"
                                              "  background-position: center center;\n"
                                              "  background-size: 50% 50%;")
        self.limit_time_tuesday.setObjectName("checkBox_3")
        self.timeEdit_3 = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit_3.setGeometry(QtCore.QRect(470, 220, 118, 24))
        self.timeEdit_3.setObjectName("timeEdit_3")
        self.limit_time_wednesday = QtWidgets.QCheckBox(self.centralwidget)
        self.limit_time_wednesday.setGeometry(QtCore.QRect(220, 220, 241, 20))
        self.limit_time_wednesday.setStyleSheet("border: 1px solid #adb5bd;\n"
                                                "  border-radius: 0.25em;\n"
                                                "  margin-right: 0.5em;\n"
                                                "  background-repeat: no-repeat;\n"
                                                "  background-position: center center;\n"
                                                "  background-size: 50% 50%;")
        self.limit_time_wednesday.setObjectName("checkBox_4")
        self.timeEdit_4 = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit_4.setGeometry(QtCore.QRect(470, 260, 118, 24))
        self.timeEdit_4.setObjectName("timeEdit_4")
        self.limit_time_thursday = QtWidgets.QCheckBox(self.centralwidget)
        self.limit_time_thursday.setGeometry(QtCore.QRect(220, 260, 241, 20))
        self.limit_time_thursday.setStyleSheet("border: 1px solid #adb5bd;\n"
                                               "  border-radius: 0.25em;\n"
                                               "  margin-right: 0.5em;\n"
                                               "  background-repeat: no-repeat;\n"
                                               "  background-position: center center;\n"
                                               "  background-size: 50% 50%;")
        self.limit_time_thursday.setObjectName("checkBox_5")
        self.timeEdit_5 = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit_5.setGeometry(QtCore.QRect(470, 300, 118, 24))
        self.timeEdit_5.setObjectName("timeEdit_5")
        self.limit_time_friday = QtWidgets.QCheckBox(self.centralwidget)
        self.limit_time_friday.setGeometry(QtCore.QRect(220, 300, 241, 20))
        self.limit_time_friday.setStyleSheet("border: 1px solid #adb5bd;\n"
                                             "  border-radius: 0.25em;\n"
                                             "  margin-right: 0.5em;\n"
                                             "  background-repeat: no-repeat;\n"
                                             "  background-position: center center;\n"
                                             "  background-size: 50% 50%;")
        self.limit_time_friday.setObjectName("checkBox_6")
        self.timeEdit_6 = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit_6.setGeometry(QtCore.QRect(470, 460, 118, 24))
        self.timeEdit_6.setObjectName("timeEdit_6")
        self.limit_time_saturday = QtWidgets.QCheckBox(self.centralwidget)
        self.limit_time_saturday.setGeometry(QtCore.QRect(220, 460, 241, 20))
        self.limit_time_saturday.setStyleSheet("border: 1px solid #adb5bd;\n"
                                               "  border-radius: 0.25em;\n"
                                               "  margin-right: 0.5em;\n"
                                               "  background-repeat: no-repeat;\n"
                                               "  background-position: center center;\n"
                                               "  background-size: 50% 50%;")
        self.limit_time_saturday.setObjectName("checkBox_7")
        self.timeEdit_7 = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit_7.setGeometry(QtCore.QRect(470, 490, 118, 24))
        self.timeEdit_7.setObjectName("timeEdit_7")
        self.limit_time_sunday = QtWidgets.QCheckBox(self.centralwidget)
        self.limit_time_sunday.setGeometry(QtCore.QRect(220, 490, 241, 20))
        self.limit_time_sunday.setStyleSheet("border: 1px solid #adb5bd;\n"
                                             "  border-radius: 0.25em;\n"
                                             "  margin-right: 0.5em;\n"
                                             "  background-repeat: no-repeat;\n"
                                             "  background-position: center center;\n"
                                             "  background-size: 50% 50%;")
        self.limit_time_sunday.setObjectName("checkBox_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Ограничение доступа с понедельника по пятницу"))
        self.turn_parental_control.setText(_translate("MainWindow", "Родительский контроль"))
        self.pushButton.setText(_translate("MainWindow", "Компьютер"))
        self.pushButton_2.setText(_translate("MainWindow", "Программы"))
        self.pushButton_3.setText(_translate("MainWindow", "Интернет"))
        self.pushButton_4.setText(_translate("MainWindow", "Общение"))
        self.pushButton_5.setText(_translate("MainWindow", "Контроль содержания"))
        self.button_details.setText(_translate("MainWindow", "Подробнее..."))
        self.label.setText(_translate("MainWindow", f"{self.username} - текущий пользователь"))
        self.label_2.setText(_translate("MainWindow", "Рабочие дни"))
        self.label_3.setText(_translate("MainWindow", "Выходные дни"))
        self.label_5.setText(_translate("MainWindow", "Ограничение доступа в субботу и воскресенье"))
        self.limit_time_monday.setText(_translate("MainWindow", "Ограничить время (понедельник)"))
        self.limit_time_tuesday.setText(_translate("MainWindow", "Ограничить время (вторник)"))
        self.limit_time_wednesday.setText(_translate("MainWindow", "Ограничить время (среда)"))
        self.limit_time_thursday.setText(_translate("MainWindow", "Ограничить время (четверг)"))
        self.limit_time_friday.setText(_translate("MainWindow", "Ограничить время (пятница)"))
        self.limit_time_saturday.setText(_translate("MainWindow", "Ограничить время (суббота)"))
        self.limit_time_sunday.setText(_translate("MainWindow", "Ограничить время (воскресенье)"))
        self.menu.setTitle(_translate("MainWindow", "Справка"))
        self.action.setText(_translate("MainWindow", "Читать"))

        self.button_details.clicked.connect(self.handler_details)
        self.turn_parental_control.clicked.connect(self.handler_turn_parental_control)
        self.limit_time_day = {
            self.limit_time_monday.text(): self.limit_time_monday,
            self.limit_time_tuesday.text(): self.limit_time_tuesday,
            self.limit_time_wednesday.text(): self.limit_time_wednesday,
            self.limit_time_thursday.text(): self.limit_time_thursday,
            self.limit_time_friday.text(): self.limit_time_friday,
            self.limit_time_saturday.text(): self.limit_time_saturday,
            self.limit_time_sunday.text(): self.limit_time_sunday,
        }
        for limit_time_day in self.limit_time_day.values():
            limit_time_day.clicked.connect(self.limit_time)


class UiDetailsWindow:
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_close = QtWidgets.QPushButton(self.centralwidget)
        self.button_close.setGeometry(QtCore.QRect(40, 520, 113, 32))
        self.button_close.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 50, 711, 401))
        self.textBrowser.setObjectName("textBrowser")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(40, 490, 731, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Справка"))
        self.button_close.setText(_translate("MainWindow", "❌ Закрыть"))
        self.button_close.clicked.connect(self.handler_close)
        self.textBrowser.setHtml(_translate("MainWindow",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:600;\">Возможности программы &quot;Родительский контроль&quot;</span></p>\n"
                                            "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:24pt; font-weight:600;\"><br /></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">1) Создание расписаний доступа к компьютеру для ребёнка. Блок &quot;Компьютер&quot;;</span></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">2) Добавление запрещённых для открытия программ. Блок &quot;Программы&quot;;</span></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">3) Добавление запрещённых для просмотра сайтов. Блок &quot;Интернет&quot;;</span></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">4) Ограничение программ для общения. Блок &quot;Общение&quot;;</span></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">5) Ограничение доступа к сайтам, где встречаются запрещённые слова. Блок &quot;Контроль содержания&quot;;</span></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">6) Получить краткую информацию о программе. Кнопка &quot;Подробнее...&quot;</span></p>\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">* Использование данной программы для незаконных целей запрещено!</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Справка"))

    def handler_close(self):
        self.close()
